package net.uoneweb.android.til.ui.pager.chars

object TlmPagerCodes {
    val CtrlBeginFreeWord = PagerCode("*2*2")
    val CtrlBeginFixedWord = PagerCode("*4*4")
    val CtrlEnd = PagerCode("#")

    val SingleNum1 = PagerCode("1")
    val SingleNum2 = PagerCode("2")
    val SingleNum3 = PagerCode("3")
    val SingleNum4 = PagerCode("4")
    val SingleNum5 = PagerCode("5")
    val SingleNum6 = PagerCode("6")
    val SingleNum7 = PagerCode("7")
    val SingleNum8 = PagerCode("8")
    val SingleNum9 = PagerCode("9")
    val SingleNum0 = PagerCode("0")

    val Num1 = PagerCode("96")
    val Num2 = PagerCode("97")
    val Num3 = PagerCode("98")
    val Num4 = PagerCode("99")
    val Num5 = PagerCode("90")
    val Num6 = PagerCode("06")
    val Num7 = PagerCode("07")
    val Num8 = PagerCode("08")
    val Num9 = PagerCode("09")
    val Num0 = PagerCode("00")

    val KanaA = PagerCode("11")
    val KanaI = PagerCode("12")
    val KanaU = PagerCode("13")
    val KanaE = PagerCode("14")
    val KanaO = PagerCode("15")

    val KanaKa = PagerCode("21")
    val KanaKi = PagerCode("22")
    val KanaKu = PagerCode("23")
    val KanaKe = PagerCode("24")
    val KanaKo = PagerCode("25")

    val KanaSa = PagerCode("31")
    val KanaSi = PagerCode("32")
    val KanaSu = PagerCode("33")
    val KanaSe = PagerCode("34")
    val KanaSo = PagerCode("35")

    val KanaTa = PagerCode("41")
    val KanaTi = PagerCode("42")
    val KanaTu = PagerCode("43")
    val KanaTe = PagerCode("44")
    val KanaTo = PagerCode("45")

    val KanaNa = PagerCode("51")
    val KanaNi = PagerCode("52")
    val KanaNu = PagerCode("53")
    val KanaNe = PagerCode("54")
    val KanaNo = PagerCode("55")

    val KanaHa = PagerCode("61")
    val KanaHi = PagerCode("62")
    val KanaHu = PagerCode("63")
    val KanaHe = PagerCode("64")
    val KanaHo = PagerCode("65")

    val KanaMa = PagerCode("71")
    val KanaMi = PagerCode("72")
    val KanaMu = PagerCode("73")
    val KanaMe = PagerCode("74")
    val KanaMo = PagerCode("75")

    val KanaYa = PagerCode("81")
    val KanaYu = PagerCode("83")
    val KanaYo = PagerCode("85")

    val KanaRa = PagerCode("91")
    val KanaRi = PagerCode("92")
    val KanaRu = PagerCode("93")
    val KanaRe = PagerCode("94")
    val KanaRo = PagerCode("95")

    val KanaWa = PagerCode("01")
    val KanaWo = PagerCode("02")
    val KanaN = PagerCode("03")

    val KanaDaku = PagerCode("04")
    val KanaHanDaku = PagerCode("05")

    val AlphaA = PagerCode("16")
    val AlphaB = PagerCode("17")
    val AlphaC = PagerCode("18")
    val AlphaD = PagerCode("19")
    val AlphaE = PagerCode("10")
    val AlphaF = PagerCode("26")
    val AlphaG = PagerCode("27")
    val AlphaH = PagerCode("28")
    val AlphaI = PagerCode("29")
    val AlphaJ = PagerCode("20")
    val AlphaK = PagerCode("36")
    val AlphaL = PagerCode("37")
    val AlphaM = PagerCode("38")
    val AlphaN = PagerCode("39")
    val AlphaO = PagerCode("30")
    val AlphaP = PagerCode("46")
    val AlphaQ = PagerCode("47")
    val AlphaR = PagerCode("48")
    val AlphaS = PagerCode("49")
    val AlphaT = PagerCode("40")
    val AlphaU = PagerCode("56")
    val AlphaV = PagerCode("57")
    val AlphaW = PagerCode("58")
    val AlphaX = PagerCode("59")
    val AlphaY = PagerCode("50")
    val AlphaZ = PagerCode("66")

    val SpQuestion = PagerCode("67")
    val SpExclamation = PagerCode("68")
    val SpHyphen = PagerCode("69")
    val SpSlash = PagerCode("60")
    val SpYen = PagerCode("76")
    val SpAmpersand = PagerCode("77")
    val SpClock = PagerCode("78")
    val SpTel = PagerCode("79")
    val SpCup = PagerCode("70")
    val SpParenthesesLeft = PagerCode("82")
    val SpParenthesesRight = PagerCode("84")

    /**
     * Asterisk(*)
     */
    val SpAsterisk = PagerCode("86")

    // #
    val SpSharp = PagerCode("87")

    /**
     *  Space
     */
    val SpSpace = PagerCode("88")
    val SpHeart = PagerCode("89")

    val IconHappy = PagerCode("1*2")
    val IconSmile = PagerCode("1*4")
    val IconCry = PagerCode("1*6")
    val IconSad = PagerCode("1*0")
    val IconScream = PagerCode("2*2")
    val IconWink = PagerCode("2*4")
    val IconAngry = PagerCode("2*6")
    val IconUpset = PagerCode("2*0")
    val IconGood = PagerCode("3*2")
    val IconHandScissors = PagerCode("3*4")
    val IconHandPaper = PagerCode("3*6")
    val IconHandRock = PagerCode("3*0")
    val IconSunny = PagerCode("4*2")
    val IconCloudy = PagerCode("4*4")
    val IconRainy = PagerCode("4*6")
    val IconSnowy = PagerCode("4*0")
    val IconHeart = PagerCode("5*2")
    val IconBrokenHeart = PagerCode("5*4")
    val IconSuper = PagerCode("5*6")
    val IconMuscle = PagerCode("5*0")
    val IconTrain = PagerCode("6*2")
    val IconCar = PagerCode("6*4")
    val IconHome = PagerCode("6*6")
    val IconPhone = PagerCode("6*0")
    val IconBeer = PagerCode("7*2")
    val IconCutlery = PagerCode("7*4")
    val IconCake = PagerCode("7*6")
    val IconPager = PagerCode("7*0")
    val IconKaraoke = PagerCode("8*2")
    val IconTv = PagerCode("8*4")
    val IconFlower = PagerCode("8*6")
    val IconPoop = PagerCode("8*0")

    val Func1Secret = PagerCode("0*2")
    val Func2SmallChar = PagerCode("0*4")
    val Func3Reminder = PagerCode("0*6")
}
